dataset:
  images_dir: "../UnifiedDataset"
  labels_csv: "../UnifiedDataset/labels.csv"
  image_size: 224
  val_ratio: 0.2
  test_only:
    - FireMan

dataloader:
  pin_memory: true
  prefetch_factor: 4
  num_workers: 10
  persistent_workers: true

training:
  model_name: "resnet18"
  freeze_backbone: false        # If true, only train the classification head (fc layer)
  lr: 0.0001
  weight_decay: 0.0001
  batch_size: 256
  num_epochs: 150
  early_stopping: 10
  print_every: 5
  max_batches_per_epoch:
  update_lr_epoch_num: 3
  lr_factor: 0.5
  acc_threshold: 0.1

wandb:
  entity: "WildFire_Detector"
  project: "Phase2_ResNet18"

checkpoint:
  path: "best_model"
